### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by khodor14** [neherlab/pangraph#22]
I tried to install pangraph

after running the command `julia --project=. -e 'using Pkg; Pkg.build()'

I got : 
` Building Conda ───→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/6cdc8832ba11c7695f494c9d9a1c31e90959ce0f/build.log`
    Building PyCall ──→ `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/4ba3651d33ef76e24fef6a598b63ffd1c5e1cd17/build.log`
    Building PanGraph → `~/Desktop/pangraph/deps/build.log`
`

now entering the PERL through
`julia --project=.
`
will jump to julia 

`   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.7.2 (2022-02-06)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> `

now typing pangraph gives

`ERROR: UndefVarError: pangraph not defined`

Could you suggest a solution?

Thank you

**Comment by nnoll** [comment]
It looks like you were following the library installation instructions. In that case, to use the functions from the REPL, you would want to type `using PanGraph` to import functionality. I would recommend reading the documentation to see how to use the library in detail.

If you just want the command line interface, I would recommend reading through the documentation on how to install. Briefly, run  `export jc="path/to/julia/executable" make pangraph && make install`.

**Comment by khodor14** [comment]
I will try it out. 

But i strongly recommend a conda, docker or singularity. It's tough to prepare the environment and run it multiple times. 

Thank you for this tool.
