### ISSUE TITLE
The process gets into sleep status without reporting

### ISSUE THREAD

**Issue by HaimAshk** [neherlab/pangraph#23]
Hi,

Thanks for developing PanGraph, I am looking forward to using it! After some complications, I managed to install it and run it successfully using the E-coli dataset. I'm now trying to run it on my dataset, with 163 strains of the same bacterial species. Unfortunately, it gets to only approximately 70% of the aligning pairs step and does not progress anymore (get into S status for days). Any advice on how to figure out where it gets stuck and how to solve it?

This is what the top line looks like:
`PR   NI    VIRT    RES      SHR       S  %CPU %MEM     TIME+        COMMAND`
`20   0 9516696 4.244g 164740 S   0.0      0.2           320:22.34 pangraph`

Thanks!

**Comment by nnoll** [comment]
We encountered this issue independently and a potential fix is already made in PR #20. You could try building off of that branch and seeing if it solves your issue. We should merge it into master soon. If this doesn't solve your issue, and you don't mind sharing your data, I can see what the underlying cause of the deadlock is.

**Comment by HaimAshk** [comment]
Thanks a lot for the quick response! 
Yes, this PR #20 solved the issue for my dataset. Thanks!

**Comment by HaimAshk** [comment]
Hi again,

I don't know if it is a related problem, but now the polishing step fails with the following error after a while (~8%):

Any advice?

Thanks!
Haim

```
KERROR: TaskFailedException
Stacktrace:
 [1] wait
   @ ./task.jl:334 [inlined]
 [2] threading_run(func::Function)
   @ Base.Threads ./threadingconstructs.jl:38
 [3] macro expansion
   @ ./threadingconstructs.jl:97 [inlined]
 [4] realign!(g::PanGraph.Graphs.Graph; accept::PanGraph.var"#20#22", case::Bool)
   @ PanGraph.Graphs 
Programs/miniconda3/envs/PanGraph_0.41.PR20/installation/pangraph/src/graph.jl:588
 [5] (::PanGraph.var"#19#21")(args::Vector{String})
   @ PanGraph 
Programs/miniconda3/envs/PanGraph_0.41.PR20/installation/pangraph/src/polish.jl:43
 [6] run(cmd::PanGraph.Commands.Command, args::Vector{String})
   @ PanGraph.Commands 
Programs/miniconda3/envs/PanGraph_0.41.PR20/installation/pangraph/src/args.jl:182
 [7] main(args::Vector{String})
   @ PanGraph 
Programs/miniconda3/envs/PanGraph_0.41.PR20/installation/pangraph/src/PanGraph.jl:87
 [8] julia_main()
   @ PanGraph 
Programs/miniconda3/envs/PanGraph_0.41.PR20/installation/pangraph/src/PanGraph.jl:92
 [9] top-level scope
   @ none:1

    nested task error: failed process: Process(`mafft --auto --nuc /dev/stdin`, ProcessSignaled(1)) [0]
    
    Stacktrace:
     [1] pipeline_error
       @ ./process.jl:531 [inlined]
     [2] run(::Base.CmdRedirect; wait::Bool)
       @ Base ./process.jl:446
     [3] mafft(block::PanGraph.Graphs.Blocks.Block, case::Bool)
       @ PanGraph.Graphs.Shell 
Programs/miniconda3/envs/PanGraph_0.41.PR20/installation/pangraph/src/cmd.jl:87
     [4] macro expansion
       @ 
Programs/miniconda3/envs/PanGraph_0.41.PR20/installation/pangraph/src/graph.jl:593 [inlined]
     [5] (::PanGraph.Graphs.var"#445#threadsfor_fun#92"{PanGraph.var"#20#22", Bool, ProgressMeter.Progress, Vector{PanGraph.Graphs.Blocks.Block}})(onethread::Bool)
       @ PanGraph.Graphs ./threadingconstructs.jl:85
     [6] (::PanGraph.Graphs.var"#445#threadsfor_fun#92"{PanGraph.var"#20#22", Bool, ProgressMeter.Progress, Vector{PanGraph.Graphs.Blocks.Block}})()
       @ PanGraph.Graphs ./threadingconstructs.jl:52
```

**Comment by nnoll** [comment]
Is this with the example dataset or your personal collection? Mafft seems to throw an error so something is off about the input sequences. Would you mind sharing your output pangraph.json file for me to zero in on the issue?

**Comment by HaimAshk** [comment]
Its for my dataset. I have not tried this step for the Ecoli example (I can try).
Sure, no problem to share with you. Can I send it to you more privately via email or something?
Thanks!

**Comment by nnoll** [comment]
Yes! Please email me at nbnoll@eml.cc
